<a href="https://colab.research.google.com/github/Sreerag3/IHUB_PROJECTS/blob/main/Main%20July%20fault%20refernce%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = pd.read_csv('/content/July raw data.csv')
print(data.shape)
data.head()

(47716, 45)

,startDate,startTime,endDate,endTime,VehicleNum,vehicleModel,groupName,driverName,StartLatGPS,StartLongGPS,...,stoppage_count,hard_curving_count,dms_tampering,lm_tao_count,dms_driver_drowsy_count,dms_driver_asleep_count,dms_driver_smoking_count,dms_driver_distracted_count,dms_driver_on_phone_count,dms_no_seat_belt_count
0,01-07-2023,05:58:54,01-07-2023,06:22:28,MH40BG2596,Eicher 10.75,Hansa-Aapli-Red-Bus,Rakesh Nandlal Meshram,21.141287,79.079645,...,0,0,NaN,0,0,0,0,0,0,0
1,01-07-2023,05:29:48,01-07-2023,05:44:47,MH40BG2596,Eicher 10.75,Hansa-Aapli-Red-Bus,Rakesh Nandlal Meshram,21.116420,79.019128,...,1,0,NaN,0,0,0,0,0,0,0
2,01-07-2023,06:06:08,01-07-2023,06:35:20,MH40BG7476,Eicher 10.75,Hansa-Aapli-Red-Bus,Vivek Choudhari,21.116597,79.013303,...,1,0,NaN,0,0,0,0,0,0,0
3,01-07-2023,06:14:58,01-07-2023,06:33:28,MH40BG1535,Tata LP09.6 BS3,Hansa-Aapli-Red-Bus,Vinod Dehankar,21.140105,79.092358,...,1,0,NaN,0,0,0,0,0,0,0
4,01-07-2023,05:35:59,01-07-2023,05:45:49,MH40BG1535,Tata LP09.6 BS3,Hansa-Aapli-Red-Bus,Vinod Dehankar,21.116942,79.019998,...,1,0,NaN,0,0,0,0,0,0,0

In [2]:
data.columns

Index(['startDate', 'startTime', 'endDate', 'endTime', 'VehicleNum',
       'vehicleModel', 'groupName', 'driverName', 'StartLatGPS',
       'StartLongGPS', 'EndLatGPS', 'EndLongGPS', 'startAddress', 'endAddress',
       'distance', 'duration', 'fuelConsumed', 'fuelWasted', 'mileage',
       'me_fcw_count', 'me_dfm_count', 'me_hmw_count', 'me_lldw_count',
       'me_pcw_count', 'me_pdz_count', 'me_rldw_count', 'me_tao_count',
       'me_twl_count', 'me_ufcw_count', 'freerun_count', 'hard_brake_count',
       'hard_curve_count', 'idling_count', 'over_acceleration_count',
       'speeding_count', 'stoppage_count', 'hard_curving_count',
       'dms_tampering', 'lm_tao_count', 'dms_driver_drowsy_count',
       'dms_driver_asleep_count', 'dms_driver_smoking_count',
       'dms_driver_distracted_count', 'dms_driver_on_phone_count',
       'dms_no_seat_belt_count'],
      dtype='object')

In [3]:
data = data[['endDate', 'VehicleNum', 'groupName', 'driverName', 'distance', 'me_fcw_count', 'me_hmw_count',
             'me_pcw_count', 'me_lldw_count', 'me_rldw_count']]
data.head()

,endDate,VehicleNum,groupName,driverName,distance,me_fcw_count,me_hmw_count,me_pcw_count,me_lldw_count,me_rldw_count
0,01-07-2023,MH40BG2596,Hansa-Aapli-Red-Bus,Rakesh Nandlal Meshram,11.255,0,0,0,0,0
1,01-07-2023,MH40BG2596,Hansa-Aapli-Red-Bus,Rakesh Nandlal Meshram,7.568,0,0,0,0,0
2,01-07-2023,MH40BG7476,Hansa-Aapli-Red-Bus,Vivek Choudhari,17.364,0,0,0,0,0
3,01-07-2023,MH40BG1535,Hansa-Aapli-Red-Bus,Vinod Dehankar,9.367,0,0,1,1,0
4,01-07-2023,MH40BG1535,Hansa-Aapli-Red-Bus,Vinod Dehankar,7.133,0,0,0,1,0

In [ ]:
# start_date = pd.to_datetime('2023-07-03')
# end_date = pd.to_datetime('2023-07-09')

# filtered_df = df[(df['endDate'] >= start_date) | (df['endDate'] <= end_date)]
# filtered_df['endDate'].value_counts()

In [4]:
df = data.copy()

In [5]:
from datetime import datetime

def custom_date_parser(date_str):
    return datetime.strptime(date_str, '%d-%m-%Y')

df['endDate'] = df['endDate'].apply(custom_date_parser)
dfs = []


day_list = [(1, 2), (3, 9), (10, 16), (17, 23), (24, 30), (31, 31)]

for day in day_list:

  start_date = datetime(2023, 7, day[0])
  end_date = datetime(2023, 7, day[1])

  mask = (df['endDate'] >= start_date) & (df['endDate'] <= end_date)
  filtered_df = df[mask]

  filtered_df.reset_index(drop=True, inplace=True)
  dfs.append(filtered_df)

In [6]:
dfs[0].to_excel('tested(1).xlsx')

In [7]:
dfs[1].to_excel('tested(2).xlsx')

In [8]:
dfs[2].to_excel('tested(3).xlsx')

In [9]:
dfs[3].to_excel('tested(4).xlsx')

In [10]:
dfs[4].to_excel('tested(5).xlsx')

In [11]:
dfs[5].to_excel('tested(6).xlsx')

In [12]:
dfs[1].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10792 entries, 0 to 10791
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   endDate        10792 non-null  datetime64[ns]
 1   VehicleNum     10792 non-null  object
 2   groupName      10792 non-null  object
 3   driverName     8891 non-null   object
 4   distance       10792 non-null  float64
 5   me_fcw_count   10792 non-null  int64
 6   me_hmw_count   10792 non-null  int64
 7   me_pcw_count   10792 non-null  int64
 8   me_lldw_count  10792 non-null  int64
 9   me_rldw_count  10792 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 843.2+ KB

In [13]:
dfs[1]['VehicleNum'] = dfs[1]['VehicleNum'].astype(str)

<ipython-input-13-9b20d528cd57>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[1]['VehicleNum'] = dfs[1]['VehicleNum'].astype(str)

In [24]:
print(dfs[1].shape)
values_to_drop = ['MH31EM0397', 'MH40BG1208','MH40BG7476','MH40BG1076','MH31EM0417','MH40BG0841','MH40BG0869',
                      'MH40BG3238','MH40BG0870','MH40BG1081','MH40BG1085','MH40BG1209','MH40BG1215','MH40BG7470',
                      'MH31EM0391','MH31FC0377','MH31FC0944','MH31EM0392','MH31FC0943','MH31FC0945','MH31FC0946',
                      'MH31FC0966','MH31FC0970','MH31FC0980','MH31EM0409','MH40BG1161','MH40AT0460','MH40Y6891',
                      'MH40BG2006','MH40BG7436','MH40BG2008']

dfs[1] = dfs[1][~dfs[1]['VehicleNum'].isin(values_to_drop)]

print(dfs[1].shape)

(9330, 10)
(9330, 10)

In [25]:
print(dfs[2].shape)
values_to_drop = ['MH40BG0869', 'MH31EM0395','MH40BG1081','MH40BG1209','MH40BG1073',
                      'MH40BG1085','MH31EM0396','MH40BG2596','MH40BG7470','MH31EM0397','MH31EM0417',
                      'MH40BG1076','MH40BG1208','MH40BG3238','MH40BG1215','MH31EM0391','MH31FC0424',
                      'MH31FC0944','MH31FC0943','MH31FC0945','MH31FC0966','MH31FC0980','MH31FC0377','MH31FC0378',
                      'MH40BG1549','MH40BG3460','MH31EM0409','MH40BG1161','MH40AT0460','MH40Y6891','MH40BG2006',
                      'MH40BG7436','MH40BG2008']

dfs[2] = dfs[2][~dfs[2]['VehicleNum'].isin(values_to_drop)]

print(dfs[2].shape)

(9705, 10)
(9705, 10)

In [26]:
print(dfs[3].shape)
values_to_drop = ['MH40BG1083', 'MH40BG0842','MH40BG1085','MH31EM0417','MH40BG1076','MH40BG1208',
                      'MH40BG3238','MH31EM0397','MH40BG1215','MH31FC0406','MH31FC0415','MH31FC0947','MH31FC0939',
                      'MH31FC0942','MH40BG1543','MH31EM0427','MH40BG2981','MH40BG1548','MH31EM0409','MH40BG1161',
                      'MH40BG2006','MH40BG7436','MH40BG7375','MH40BG2008','MH40Y6893','MH40AT0460','MH40Y6891','MH40Y6897']

dfs[3] = dfs[3][~dfs[3]['VehicleNum'].isin(values_to_drop)]

print(dfs[3].shape)

(9969, 10)
(9969, 10)

In [27]:
print(dfs[4].shape)
values_to_drop = ['MH40BG0869', 'MH40BG0841','MH40BG0842','MH40BG2597','MH40BG1085','MH31EM0396','MH40BG2596',
                      'MH40BG7470','MH40BL3842','MH40BG1208','MH40BG1076','MH40BG1083','MH40BG3238','MH31EM0397','MH40BL3833',
                      'MH31EM0395','MH40BG1081','MH40BG1209','MH40BG1215','MH31EM0417','MH31EM0391','MH31FC0216','MH31FC0406',
                      'MH31FC0944','MH31FC0939','MH31FC0947','MH31EM0392','MH31EM0389','MH31FC0382','MH31FC0424','MH31FC0942',
                      'MH31FC0945','MH31FC0946','MH31FC0377','MH40BG1543','MH40BG1551','MH40BG2981','MH40BG1548','MH40BG3460',
                      'MH31EM0409','MH40BG1161','MH40BG2980','MH31EM0423','MH40BG1549','MH31EM0425','MH40AT0182','MH40Y6893',
                      'MH40AT0460','MH40Y6891','MH40Y6895','MH40BG2008']

dfs[4] = dfs[4][~dfs[4]['VehicleNum'].isin(values_to_drop)]

print(dfs[4].shape)

(8490, 10)
(8490, 10)

In [28]:
combined_df = pd.concat([dfs[0],dfs[1], dfs[2], dfs[3],dfs[4],dfs[5]], axis=0, ignore_index=True)

In [ ]:
# data[data['groupName'] == 'Tra'].index

In [29]:
count_lists = ['distance', 'me_fcw_count','me_hmw_count', 'me_pcw_count', 'me_lldw_count',	'me_rldw_count']
data_ = combined_df.groupby(['groupName', 'driverName'])[count_lists].sum().reset_index()
print(data_.shape)
data_.head()

(408, 8)

,groupName,driverName,distance,me_fcw_count,me_hmw_count,me_pcw_count,me_lldw_count,me_rldw_count
0,Hansa-Aapli-Red-Bus,Adil Shekh,87.253,7,90,29,0,0
1,Hansa-Aapli-Red-Bus,Afsar Shaikh,871.901,0,0,0,0,0
2,Hansa-Aapli-Red-Bus,Akash Wankhede,93.294,0,24,22,2,0
3,Hansa-Aapli-Red-Bus,Amit Ram Mahlar,1987.710,38,731,398,92,6
4,Hansa-Aapli-Red-Bus,Amitkumar Deshraj Soni,2200.390,21,486,258,18,36

In [ ]:
# rem_col = ['MH31EM0391']

# data_ = data_[~data_['VehicleNum'].isin(rem_col)]
# print(data_.shape)

In [ ]:
# with pd.ExcelWriter('output.xlsx') as writer:
#   for g_name, g_data in data_.groupby('groupName'):
#     g_data.to_excel(writer, sheet_name=g_name, index=False)

In [30]:
print(data['groupName'].value_counts(),'\n')
print(data_['groupName'].value_counts())

Traveltime-Aapli-Red-Bus    15466
RK-Travels-Aapli-Red-Bus    13112
Hansa-Aapli-Red-Bus         12681
Hansa-School-Bus-Fleet       5072
Hansa-Employee-Transport     1385
Name: groupName, dtype: int64

RK-Travels-Aapli-Red-Bus    138
Traveltime-Aapli-Red-Bus    136
Hansa-Aapli-Red-Bus         134
Name: groupName, dtype: int64

In [31]:
name_list = data_['groupName'].unique()
print(name_list)

for g_value in name_list:

  g_df = data_[data_['groupName'] == g_value]
  f_name = f"group_{g_value}.xlsx"
  g_df.to_excel(f_name, index=False)

['Hansa-Aapli-Red-Bus' 'RK-Travels-Aapli-Red-Bus'
 'Traveltime-Aapli-Red-Bus']

In [32]:
name_ = 'Hansa-School-Bus-Fleet'

group_df = data[data['groupName'] == 'name_']
group_df.head()

Empty DataFrame
Columns: [endDate, VehicleNum, groupName, driverName, distance, me_fcw_count, me_hmw_count, me_pcw_count, me_lldw_count, me_rldw_count]
Index: []

In [33]:
# Only for Hansa-School-Bus-Fleet

gp_df = data[data['groupName'] == 'Hansa-School-Bus-Fleet']

count_lists = ['distance', 'me_fcw_count','me_hmw_count', 'me_lldw_count',	'me_pcw_count',	'me_rldw_count']
gp_df = gp_df.groupby('VehicleNum')[count_lists].sum().reset_index()

gp_df.head()

,VehicleNum,distance,me_fcw_count,me_hmw_count,me_lldw_count,me_pcw_count,me_rldw_count
0,MH40BG1908,2793.837,34,91,159,246,431
1,MH40BG1931,1733.504,31,497,90,299,25
2,MH40BG1933,1212.890,35,406,22,155,45
3,MH40BG1934,1507.385,23,286,19,160,31
4,MH40BG1935,1411.114,38,371,43,215,81

In [34]:
gp_df.to_excel("group_Hansa-School-Bus-Fleet.xlsx")