<a href="https://colab.research.google.com/github/Sreerag3/IHUB_PROJECTS/blob/main/monthly%20alert%20sum%20analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = pd.read_csv('/content/february.csv',error_bad_lines=False)
print(data.shape)
data.head()

In [ ]:
data.columns

In [ ]:
data = data[['VehicleNum','me_fcw_count', 'me_hmw_count', 'me_lldw_count', 'me_rldw_count',
             'me_pcw_count']]
data.head()

In [ ]:
count_lists = ['me_fcw_count','me_hmw_count', 'me_lldw_count',	'me_rldw_count',	'me_pcw_count']
data_ = data.groupby(['VehicleNum'])[count_lists].sum().reset_index()
data_.head(10)

In [ ]:
sum_row = data_.sum()
data_ = data_.append(sum_row, ignore_index=True)
data_.tail()

In [64]:
data_.to_excel("Sum of alerts.xlsx")

In [ ]:
# with pd.ExcelWriter('output.xlsx') as writer:
#   for g_name, g_data in data_.groupby('groupName'):
#     g_data.to_excel(writer, sheet_name=g_name, index=False)

In [5]:
print(data_['VehicleNum'].value_counts())

TS05Z0171    1
TS09Z7684    1
TS09Z7672    1
TS09Z7669    1
TS09Z7663    1
            ..
TS08Z0203    1
TS08Z0202    1
TS08Z0198    1
TS08Z0197    1
TS9Z7662     1
Name: VehicleNum, Length: 122, dtype: int64

In [6]:
name_list = data_['groupName'].unique()
print(name_list)

for g_value in name_list:

  g_df = data_[data_['groupName'] == g_value]
  f_name = f"group_{g_value}.xlsx"
  g_df.to_excel(f_name, index=False)

KeyError: ignored

In [ ]:
name_ = 'Hansa-School-Bus-Fleet'

group_df = data[data['groupName'] == 'name_']
group_df.head()

Empty DataFrame
Columns: [VehicleNum, groupName, driverName, distance, me_fcw_count, me_hmw_count, me_lldw_count, me_pcw_count, me_rldw_count]
Index: []

In [ ]:
# Only for Hansa-School-Bus-Fleet

gp_df = data[data['groupName'] == 'Hansa-School-Bus-Fleet']

count_lists = ['distance', 'me_fcw_count','me_hmw_count', 'me_lldw_count',	'me_pcw_count',	'me_rldw_count']
gp_df = gp_df.groupby('VehicleNum')[count_lists].sum().reset_index()

gp_df.head()

,VehicleNum,distance,me_fcw_count,me_hmw_count,me_lldw_count,me_pcw_count,me_rldw_count
0,MH40BG1908,2793.837,34,91,159,246,431
1,MH40BG1931,1733.504,31,497,90,299,25
2,MH40BG1933,1212.890,35,406,22,155,45
3,MH40BG1934,1507.385,23,286,19,160,31
4,MH40BG1935,1411.114,38,371,43,215,81

In [ ]:
gp_df.to_excel("group_Hansa-School-Bus-Fleet.xlsx")