<a href="https://colab.research.google.com/github/Sreerag3/IHUB_PROJECTS/blob/main/Telangana%20Vehicle%20no%20bsed%20classifiactaion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Read the data from the CSV file
data = pd.read_csv('/content/Updated Roster.csv')

# Select relevant columns
data = data[['SERVICE No.', 'OPTD_ KMS', 'VEHICLE No.', 'Corridor']]

# Group by 'VEHICLE No.' and aggregate the 'OPTD_ KMS', 'SERVICE No.', and 'Corridor'
aggregated_data = data.groupby('VEHICLE No.').agg({'OPTD_ KMS': 'sum', 'SERVICE No.': 'unique', 'Corridor': 'unique'}).reset_index()

# Iterate through the rows and print unique SERVICE No., Corridor, and aggregated OPTD_ KMS
for index, row in aggregated_data.iterrows():
    vehicle_no = row['VEHICLE No.']
    total_optd_kms = row['OPTD_ KMS']
    unique_service_numbers = row['SERVICE No.']
    unique_corridors = row['Corridor']

    print(f"Vehicle No.: {vehicle_no}")
    print(f"Total OPTD_ KMS: {total_optd_kms}")
    print(f"Unique SERVICE No.: {unique_service_numbers}")
    print(f"Unique Corridors: {unique_corridors}")
    print("===")

# Save the result to an Excel file
aggregated_data.to_excel("Veh No based ride details.xlsx", index=False)

Vehicle No.: AP28Z0811
Total OPTD_ KMS: 900.0
Unique SERVICE No.: [9011]
Unique Corridors: [nan]
===
Vehicle No.: TS05Z0171
Total OPTD_ KMS: 14810.0
Unique SERVICE No.: [3062 1712 1832 2942 2922 2852 2882 1652 2832 2912 3042 2982 2972 2962
 3022 2862 3012]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS07Z4006
Total OPTD_ KMS: 12120.0
Unique SERVICE No.: [2722 3052 2612 2982 2622 2702 2642 2652 2732 2632 3022 2782 2662 2792]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS07Z4070
Total OPTD_ KMS: 13884.0
Unique SERVICE No.: [3032 2872 3002 1642 1622 2932 2942 3052 2992 2962 9507]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS07Z4071
Total OPTD_ KMS: 15652.0
Unique SERVICE No.: [1632 2872 3032 3002 1652 2842]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS07Z4072
Total OPTD_ KMS: 12168.0
Unique SERVICE No.: [1622 1732 2842 1632 3002 2872 3032 2982 2852 1712]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS07Z4073
Total OPTD_ KMS: 11056.0
Unique SERVICE No.: [2842 1622 2852 2872 1732 1632 3032]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS07Z4074
Total OPTD_ KMS: 15178.0
Unique SERVICE No.: [3002 2872 1642 1622 9507 1632 3032]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS07Z4089
Total OPTD_ KMS: 13414.0
Unique SERVICE No.: [1622 2912 2842 1632 2942 1642 9051 2872 3032]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS07Z4111
Total OPTD_ KMS: 1244.0
Unique SERVICE No.: [2872 3002 1622]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0028
Total OPTD_ KMS: 3612.0
Unique SERVICE No.: [2632 2982 1732 2622 2952]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0052
Total OPTD_ KMS: 10836.0
Unique SERVICE No.: [2652 2782 2662 2952 2632 2622 3012 2792 2922 2942 2962 2722 2982]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0059
Total OPTD_ KMS: 10836.0
Unique SERVICE No.: [1732 2642 2652 2662 2942 2632 2622 2702 2732 2612 2782 2792]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0116
Total OPTD_ KMS: 15652.0
Unique SERVICE No.: [1712 2992 2832 3062 1832 2932 2962 2982 1732 2852 2972 3022 2942 3012]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0122
Total OPTD_ KMS: 602.0
Unique SERVICE No.: [2622]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0126
Total OPTD_ KMS: 16954.0
Unique SERVICE No.: [3012 1732 2852 3022 1712 1832 2962 2972 2882 2912 2992 1652]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0127
Total OPTD_ KMS: 17090.0
Unique SERVICE No.: [2922 2862 2912 2972 3022 2882 1732 3012 1652 2982]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0161
Total OPTD_ KMS: 90.0
Unique SERVICE No.: [2632]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0182
Total OPTD_ KMS: 17458.0
Unique SERVICE No.: [2832 2952 2612 2982 2702 3062 2722 2632 2622 2642 2732 3052 3012 2912
 2782]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0183
Total OPTD_ KMS: 12672.0
Unique SERVICE No.: [2792 2652 3052 2612 2982 2642 2732 2782 2702 2922 2632 2722 2622]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0185
Total OPTD_ KMS: 14614.0
Unique SERVICE No.: [3052 2612 2702 2972 2722 2632 2792 2712 2782 2732 2662 2952]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0210
Total OPTD_ KMS: 15652.0
Unique SERVICE No.: [2962 3002 3032 2842 1632 2872 2852]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0214
Total OPTD_ KMS: 13691.0
Unique SERVICE No.: [2682 2842 9051 1622 2852 1632 2872 3002 3032]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS08Z0221
Total OPTD_ KMS: 13886.0
Unique SERVICE No.: [2732 2722 3052 2642 3042 2612 2622 2652 2792 2662 2702 2632 2982 2932]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0243
Total OPTD_ KMS: 1806.0
Unique SERVICE No.: [3022 2852 1732]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0248
Total OPTD_ KMS: 15724.0
Unique SERVICE No.: [3022 2882 1652 2832 2932 2962 2942 1642 3042 3012 2862]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0250
Total OPTD_ KMS: 16964.0
Unique SERVICE No.: [2972 3022 1652 2922 2862 3012 2882 2992 2832 1832 2932 1642 1712]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0251
Total OPTD_ KMS: 15220.0
Unique SERVICE No.: [2942 2862 2982 2882 2992 3022 1652 2832 1832 1712 3052 2922 2932]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0252
Total OPTD_ KMS: 15836.0
Unique SERVICE No.: [2882 1642 2932 2862 2912 2972 3022 3012 2852 9508 9036 2992 2982 2942
 1832 2832 1652]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS08Z0253
Total OPTD_ KMS: 16073.0
Unique SERVICE No.: [2862 2932 2942 9037 1642 2962 1732 3012 3022 2992 1832 9508 2922]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS08Z0255
Total OPTD_ KMS: 16928.0
Unique SERVICE No.: [3012 1652 3062 1712 1832 2932 2922 2912 2852 2972 3022 3042 2982 2882
 2862 2942 1642]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0256
Total OPTD_ KMS: 10252.0
Unique SERVICE No.: [2912 2852 3022 1652 2992 1712 2962 2982 3012 2882 2832]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS08Z0264
Total OPTD_ KMS: 460.0
Unique SERVICE No.: [3022 1832]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7618
Total OPTD_ KMS: 882.0
Unique SERVICE No.: [1642 2942]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7627
Total OPTD_ KMS: 15170.0
Unique SERVICE No.: [2852 2972 3012 3062 1832 2932 2922 2912 3042 2982 1732 3022 1642 1632]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7628
Total OPTD_ KMS: 240.0
Unique SERVICE No.: [3012]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7629
Total OPTD_ KMS: 15652.0
Unique SERVICE No.: [1652 1832 2932 2962 2852 3012 3022 2832 2982 2922 2912 2992 1712]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7638
Total OPTD_ KMS: 13996.0
Unique SERVICE No.: [1712 1832 2932 2942 2922 2962 1732 2852 2972 2952 2992 1652 1642 2912]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7655
Total OPTD_ KMS: 16856.0
Unique SERVICE No.: [1642 2962 2852 2992 2832 2982 2972 1712 1832 1732 1652 3012 3042 3052]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7677
Total OPTD_ KMS: 16254.0
Unique SERVICE No.: [2932 2942 2922 2962 3012 1652 1712 2832 1642 2912 3052 3042 2972 3022
 2992]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7679
Total OPTD_ KMS: 520.0
Unique SERVICE No.: [3022 1642]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7682
Total OPTD_ KMS: 6350.0
Unique SERVICE No.: [1832 2852 3022 2992 2952 2912 2972 2832 1712 2922]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7828
Total OPTD_ KMS: 1536.0
Unique SERVICE No.: [2712]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7880
Total OPTD_ KMS: 9337.0
Unique SERVICE No.: [2672 2692]
Unique Corridors: ['Bangalore' 'Vijayawada']
===
Vehicle No.: TS09Z7884
Total OPTD_ KMS: 9305.0
Unique SERVICE No.: [2672]
Unique Corridors: ['Bangalore']
===
Vehicle No.: TS09Z7885
Total OPTD_ KMS: 9366.0
Unique SERVICE No.: [2682 2672]
Unique Corridors: ['Vijayawada' 'Bangalore']
===
Vehicle No.: TS09Z7886
Total OPTD_ KMS: 9985.0
Unique SERVICE No.: [2672 2682 2662]
Unique Corridors: ['Bangalore' 'Vijayawada']
===
Vehicle No.: TS09Z7888
Total OPTD_ KMS: 10065.0
Unique SERVICE No.: [2692]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS09Z7889
Total OPTD_ KMS: 10013.0
Unique SERVICE No.: [2692 2672]
Unique Corridors: ['Vijayawada' 'Bangalore']
===
Vehicle No.: TS15Z0174
Total OPTD_ KMS: 8196.0
Unique SERVICE No.: [1712 3012 2982 2932 2972 3022 9032 2962 2912 2942]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS15Z0180
Total OPTD_ KMS: 12170.0
Unique SERVICE No.: [2782 2622 2702 2642 2722 3052 1642 2982 2632 2652 2612]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS15Z0193
Total OPTD_ KMS: 15296.0
Unique SERVICE No.: [2952 2612 9038 3042 2712 2632 2702 2732 2912 9031 3012 2642 2932 2582
 2592 2982]
Unique Corridors: ['Vijayawada' nan 'Others']
===
Vehicle No.: TS15Z0200
Total OPTD_ KMS: 13923.5
Unique SERVICE No.: [2642 2782 2792 2732 9037 2712 9038 2702 1732 2632]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS15Z0201
Total OPTD_ KMS: 12130.0
Unique SERVICE No.: [2592 2712 2652 2732 9038 2942 2952 2642 2782]
Unique Corridors: ['Others' 'Vijayawada' nan]
===
Vehicle No.: TS15Z0202
Total OPTD_ KMS: 14928.0
Unique SERVICE No.: [2582 2652 2792 2732]
Unique Corridors: ['Others' 'Vijayawada']
===
Vehicle No.: TS15Z0203
Total OPTD_ KMS: 14057.0
Unique SERVICE No.: [1752 2572 2782 9038 2642 2792 2652]
Unique Corridors: ['Vijayawada' 'Others' nan]
===
Vehicle No.: TS15Z0211
Total OPTD_ KMS: 14110.0
Unique SERVICE No.: [2592 2572 2712 2652 2662]
Unique Corridors: ['Others' 'Vijayawada']
===
Vehicle No.: TS15Z0218
Total OPTD_ KMS: 13302.0
Unique SERVICE No.: [2592 2582]
Unique Corridors: ['Others']
===
Vehicle No.: TS15Z0221
Total OPTD_ KMS: 12413.0
Unique SERVICE No.: [2982 2642 2712 2652 2792 9037 9038 2732 2702 2662 2722]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS15Z0223
Total OPTD_ KMS: 11234.0
Unique SERVICE No.: [2622 2712 9038 2572 2732 1712 1642 2952 3022 3042 2612 2982 1732 2632]
Unique Corridors: ['Vijayawada' nan 'Others']
===
Vehicle No.: TS15Z0224
Total OPTD_ KMS: 11026.0
Unique SERVICE No.: [2622 2632 1712 2652 2832 3052 9506 2662 1752 2952]
Unique Corridors: ['Vijayawada' nan]
===
Vehicle No.: TS15Z0228
Total OPTD_ KMS: 5717.0
Unique SERVICE No.: [1832 9038 9037 2792 2572]
Unique Corridors: ['Vijayawada' nan 'Others']
===
Vehicle No.: TS15Z0229
Total OPTD_ KMS: 5399.0
Unique SERVICE No.: [1622 9039 2712 2582]
Unique Corridors: ['Vijayawada' nan 'Others']
===
Vehicle No.: TS15Z0230
Total OPTD_ KMS: 5576.0
Unique SERVICE No.: [1712 2712]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS15Z0231
Total OPTD_ KMS: 7404.0
Unique SERVICE No.: [2952 2972 2622 2652 2782 2732 2642]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS15Z0232
Total OPTD_ KMS: 6062.0
Unique SERVICE No.: [2592 9037 2632 2982 3052 2722 2932 2792 2622 2612]
Unique Corridors: ['Others' nan 'Vijayawada']
===
Vehicle No.: TS18Z0032
Total OPTD_ KMS: 60.0
Unique SERVICE No.: [2612]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS18Z0033
Total OPTD_ KMS: 3612.0
Unique SERVICE No.: [2612 2632 3042 2782 2652 2702]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS22Z0037
Total OPTD_ KMS: 12040.0
Unique SERVICE No.: [2982 1732 2632 2622 2842 2792 2782 2722 2942 2702 2642 2612]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS36Z0010
Total OPTD_ KMS: 12808.0
Unique SERVICE No.: [2662 2952 2632 2622 2712 2722 2702 2642 2792 2942 2612 3042 2972]
Unique Corridors: ['Vijayawada']
===
Vehicle No.: TS36Z0013
Total OPTD_ KMS: 1806.0
Unique SERVICE No.: [2702 2622]
Unique Corridors: ['Vijayawada']
===